apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqlconnectors
  labels:
    app: mysqlconnectors
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqlconnectors
  template:
    metadata:
      labels:
        app: mysqlconnectors
    spec:
      containers:
      - name: mysqlconnectors
        image: basesdedatos2/mysql_connectors
        env:
          - name: MARIADB
            value: "databases-mariadb"
          - name: RABBITMQ
            value: "databases-rabbitmq"
          - name: EXTRACTQUEUE
            value: "extract"
          - name: SQL_QUEUE
            value: "sql_queue"
          - name: RABBITPASS
            valueFrom:
              secretKeyRef:
                name: databases-rabbitmq
                key: rabbitmq-password
                optional: false
          - name: ESENDPOINT
            value: quickstart-es-default
          - name: ESPASSWORD
            valueFrom:
              secretKeyRef:
                name: quickstart-es-elastic-user
                key: elastic
                optional: false
          - name: ESINDEXJOBS
            value: jobs
          - name: ESINDEXGROUPS
            value: groups