apiVersion: apps/v1
kind: Deployment
metadata:
  name: Orchestrator
  labels:
    app: Orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Orchestrator
  template:
    metadata:
      labels:
        app: Orchestrator
    spec:
      containers:
      - name: Orchestrator
        image: basesdedatos2/Orchestrator
        env:
          - name: RABBITMQ
            value: "databases-rabbitmq"
          - name: EXTRACTQUEUE
            value: "extract"
          - name: RABBITPASS
            valueFrom:
              secretKeyRef:
                name: databases-rabbitmq
                key: rabbitmq-password
                optional: false
          - name: ESENDPOINT
            value: quickstart-es-default
          - name: ESPASSWORD
            valueFrom:
              secretKeyRef:
                name: quickstart-es-elastic-user
                key: elastic
                optional: false
          - name: ESINDEXJOBS
            value: jobs
          - name: ESINDEXGROUPS
            value: groups