apiVersion: apps/v1
kind: Deployment
metadata:
  name: regexprocessor
  labels:
    app: regexprocessor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: regexprocessor
  template:
    metadata:
      labels:
        app: regexprocessor
    spec:
      containers:
      - name: regexprocessor
        image: basesdedatos2/regex_processor
        env:
          - name: RABBITMQ
            value: "databases-rabbitmq"
          - name: REGEX_QUEUE
            value: "regex_queue"
          - name: READYQUEUE
            value: "ready"
          - name: RABBITPASS
            valueFrom:
              secretKeyRef:
                name: databases-rabbitmq
                key: rabbitmq-password
                optional: false
          - name: ESENDPOINT
            value: quickstart-es-default
          - name: ESPASSWORD
            valueFrom:
              secretKeyRef:
                name: quickstart-es-elastic-user
                key: elastic
                optional: false
          - name: ESINDEXJOBS
            value: jobs
          - name: ESINDEXGROUPS
            value: groups