apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlprocessor
  labels:
    app: sqlprocessor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlprocessor
  template:
    metadata:
      labels:
        app: sqlprocessor
    spec:
      containers:
      - name: sqlprocessor
        image: basesdedatos2/sql_processor
        env:
          - name: RABBITMQ
            value: "databases-rabbitmq"
          - name: SQL_QUEUE
            value: "sql_queue"
          - name: REGEX_QUEUE
            value: "regex_queue"
          - name: RABBITPASS
            valueFrom:
              secretKeyRef:
                name: databases-rabbitmq
                key: rabbitmq-password
                optional: false
          - name: ESENDPOINT
            value: quickstart-es-default
          - name: ESPASSWORD
            valueFrom:
              secretKeyRef:
                name: quickstart-es-elastic-user
                key: elastic
                optional: false
          - name: ESINDEXJOBS
            value: jobs
          - name: ESINDEXGROUPS
            value: groups