  # -- Pasos abstractos
  # Eliminar el contenido de la carpeta "templates"
  # Ingresar las dependencias de las bases de datos (Chart.yaml)
  # Cambiar los valores necesarios del template de las bases de datos para que sean visibles en Prometheus (values.yaml)
  # -- Lineas de comando
  # helm repo update -> actualiza todos los repositorios
  # helm repo update bitnami -> actualiza el repositorio de bitnami
  # helm search repo <base de datos a buscar>  -> busca la info de la base de datos
  # helm dependency update -> descarga los archivos comprimidos de las bases de datos dentro de la carpeta desiganada
  # helm template . -> render de la app con los nuevos valores
  # helm install databases databases -> instalar el nuevo helm chart "databases" en la carpeta "databases"
  
  enablePostgreSQL: true
  enableMariaDB: false
  enableMongoDB: true
  enableECKOperator: false
  enableElasticsearch: true
  enableElasticsearchExporter: false
# -- Cambios a los valores de la base de datos PostgreSQL
  postgresql:
    auth: # Autentificacion
      database: "postgresql" # Nombre de la base de datos
    metrics: # Analisis de metricas
      enabled: true 
      serviceMonitor: # Habilitar el servicio de monitoreo
        enabled: true

# -- Cambios a los valores de la base de datos MariaD
  mariadb:
    image: 
      pullSecrets: [mariadb-secret]
      debug: true
    architecture: replication
    auth:
      existingSecret: mariadb-secret
    primary: 
      name: primary
    secondary:
      replicaCount: 2
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

# -- Cambios a los valores de la base de datos MongoDB
  mongodb:
    architecture: replicaset # Especificacion de la arquitectura de la base de datos (replicaset o standalone)
    useStatefulSet: true
    auth: # Autentificacion
     enabled: false # No pide credenciales
    replicaCount: 3 # Cantidad de replicas a utilizar
    metrics: # Analisis de metricas
     enabled: true
     serviceMonitor: # Habilitar el servicio de monitoreo
       enabled: true

# -- Cambios a los valores de la base de datos Elasticsearch
  elasticsearch:
    # Configuracion del nodo master
    master: 
      # Numero de replicas definidas para el master
      replicaCount: 1
      resources:
        requests:
          memory: "2Mi"
          cpu: "125m"
    # Configuracion del nodo de datos
    data: 
      # Numero de replicas definidas para almacenar los datos
      replicaCount: 3
      resources:
        requests:
          memory: "1Mi"
          cpu: "125m"
    # Configuracion del nodo procesador de datos
    ingest:
      # Numero de replicas definidas para el procesador de datos
      replicaCount: 1
      resources:
        requests:
          memory: "1Mi"
          cpu: "125m"
    # Configuracion del nodo coordinador
    coordinating:
      # Numero de replicas definidas para el coordinador
      replicaCount: 1
      resources:
        requests:
          memory: "1Mi"
          cpu: "125m"
    metrics:  # Habilitar el servicio de monitoreo
      enabled: true
      serviceMonitor:
        enabled: true

# -- Cambios a los valores del operador de Elasticsearch
  eck-operator:
    nameOverride: "eck-operator"
    fullnameOverride: "eck-operator"
    managedNamespaces: []

# -- Cambios a los valores del exportador de datos de Elasticsearch
  prometheus-elasticsearch-exporter:
    serviceMonitor:
      enabled: true
