  enableRabbitMQ: true
  enableMariaDB: true
  enableElasticsearchExporter: true

  rabbitmq:
    auth:
      password: "password"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true


  mariadb:
    image: 
      pullSecrets: [mariadb-secret]
      debug: true
    architecture: replication
    auth:
      existingSecret: mariadb-secret
    primary: 
      name: primary
    secondary:
      replicaCount: 2
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true


  prometheus-elasticsearch-exporter:
    serviceMonitor:
      enabled: true
