  enableRabbitMQ: true
  #enableMariaDB: false
  #enableElasticsearch: true
  enableElasticsearchExporter: true

  rabbitmq:
    auth:
      password: "password"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true


  #mariadb:
  #  image: 
  #    pullSecrets: [mariadb-secret]
  #    debug: true
  #  architecture: replication
  #  auth:
  #    existingSecret: mariadb-secret
  #  primary: 
  #    name: primary
  #  secondary:
  #    replicaCount: 2
  #  metrics:
  #    enabled: true
  #    serviceMonitor:
  #      enabled: true

#elasticsearch:
#    master: 
#      replicaCount: 1
#      resources:
#        requests:
#          memory: "2Mi"
#          cpu: "125m"
#    data: 
#      replicaCount: 3
#      resources:
#        requests:
#          memory: "1Mi"
#          cpu: "125m"
#    ingest:
#      replicaCount: 1
#      resources:
#        requests:
#          memory: "1Mi"
#          cpu: "125m"
#    coordinating:
#      replicaCount: 1
#      resources:
#        requests:
#          memory: "1Mi"
#          cpu: "125m"
#    metrics:
#      enabled: true
#      serviceMonitor:
#        enabled: true


  prometheus-elasticsearch-exporter:
    serviceMonitor:
      enabled: true
