apiVersion: apps/v1
kind: Deployment
metadata:
  name: jatsxml_processor
  labels:
    app: jatsxml_processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jatsxml_processor
  template:
    metadata:
      labels:
        app: jatsxml_processor
    spec:
      containers:
      - name: jatsxml_processor
        image: basesdedatos2/jatsxml_processor
        env:
          - name: DATAFROMK8S
            value: "Hey"
          - name: RABBITMQ
            value: "databases-rabbitmq"
          - name: RABBITQUEUE
            value: "queue"
          - name: RABBITPASS
            valueFrom:
              secretKeyRef:
                name: databases-rabbitmq
                key: rabbitmq-password
                optional: false
          - name: ESENDPOINT
            value: quickstart-es-default
          - name: ESPASSWORD
            valueFrom:
              secretKeyRef:
                name: quickstart-es-elastic-user
                key: elastic
                optional: false
          - name: ESINDEX
            value: docidx