apiVersion: apps/v1
kind: Deployment
metadata:
  name: loader
  labels:
    app: loader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loader
  template:
    metadata:
      labels:
        app: loader
    spec:
      containers:
      - name: loader
        image: basesdedatos2/loader
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: BIORXIV
            value: "https://api.biorxiv.org/covid19/0"
          - name: RABBITMQ
            value: "databases-rabbitmq"
          - name: RABBITPASS
            valueFrom:
              secretKeyRef:
                name: databases-rabbitmq
                key: rabbitmq-password
                optional: false
          - name: MARIADB
            value: "databases-mariadb"
          - name: MARIAPASS
            valueFrom:
              secretKeyRef:
                name: databases-mariadb
                key: mariadb-password
                optional: false
          - name: INQUEUE
            value: "EntryQueue"
          - name: OUTQUEUE
            value: "OutputQueue"
          - name: ELASTIC
            value: quickstart-es-default
          - name: ELASTICPASS
            valueFrom:
              secretKeyRef:
                name: quickstart-es-elastic-user
                key: elastic
                optional: false
          - name: ELASTICINDEX
            value: jobs
          - name: ELASTICINDEX
            value: groups